//import './0_demos/test'


//import './0_demos/01_attributes'
//import './0_demos/02_matrix'
//import './0_demos/03_movePolygons'
//import './0_demos/04_atlas'
//import './0_demos/05_manyFigures'
//import './0_demos/06_simpleProfile'
//import './0_demos/07_profileByPoints'
//import './0_demos/07_z1_doubleProfile'
//import './0_demos/08_structureRooms'
import './0_demos/08_z1_structureRoomsAnimate'
//import './0_demos/09_structureBreaksEasy'
//import './0_demos/10_tiles'
//import './0_demos/11_collisions'
//import './0_demos/12_tilesConnect'
//import './0_demos/13_waveFuncAll'
//import './0_demos/14_structureBricks'

